version: '3.8'

services:
  app:
    container_name: sicuan-api
    build: 
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env.production
    restart: unless-stopped
    networks:
      - sicuan-network

networks:
  sicuan-network:
    driver: bridge