services:
  app:
    container_name: sicuan-api
    build: 
      context: .
      target: runner 
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
    env_file:
      - .env
    command: npm run start